<?php
/**
* This module introduces an ajax solution for the resources page
*/


function ajax_resources_menu() {

  $items = array();

  $items['resources-page'] = array(
    'title' => 'Resources',
    'page callback' => 'resources_form',
    'access arguments' => array('access content'),	
	'file' => 'ajax_resources.form.inc',
    'type' => MENU_CALLBACK
  );

  $items['resources-view-json/%/%/%'] = array(
    'title' => 'Resources',
    'page callback' => 'views_get_view_results',
	'page arguments' => array(1,2,3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

/*** taxonomy menus ***/
  
  $items['type-tree'] = array(
    'title' => 'Resources',
    'page callback' => 'type_tree',
    'access arguments' => array('access content'),
	'file' => 'ajax_resources.type.inc'
  );
  
  $items['topic-tree'] = array(
    'title' => 'Resources',
    'page callback' => 'topic_tree',
    'access arguments' => array('access content'),
	'file' => 'ajax_resources.topic.inc',
    'type' => MENU_CALLBACK
  );
  
/*** group/nid menu ***/
  
  $items['group-tree'] = array(
    'title' => 'groups',
    'page callback' => 'group_tree',
    'access arguments' => array('access content'),
	'file' => 'ajax_resources.group.inc'
  );
  

  return $items;
}

/**
* This function gets called in the browser address bar for:
* "http://yourhost/my_module/form" or
* "http://yourhost/?q=my_module/form". It will generate
* a page with this form on it.
*/



function views_get_view_results($tid,$tid2,$og_id) {
  $viewname = 'resources_view';
  $view = views_get_view($viewname);
	$newTid2 = str_replace("-","+", $tid2);
/*$args = array($tid,$tid2,$og_id); */
$args = array($tid,$newTid2,$og_id);
	$output = $view->preview('default', $args);
	if (empty($view->result)) {
		print "no result";
	}
  $view->render();
  return drupal_json($view->result);
}



 
function ajax_resources_theme() {
   return array(
      'ajax_resources_javascript' => array(
         'arguments' => array(),
      ),
   );   
}

function ajax_resources_init() {
  theme('ajax_resources_javascript');
     drupal_add_css(drupal_get_path('module', 'ajax_resources') . '/ajax_resources.css');
}

function theme_ajax_resources_javascript() {
  drupal_add_js(drupal_get_path('module', 'ajax_resources') . '/ajax_resources.js');
}


/**
 * This function will return a vocabulary object which matches the
 * given name. Will return null if no such vocabulary exists.
 *
 * @param String $vocabulary_name
 *   This is the name of the section which is required
 * @return Object
 *   This is the vocabulary object with the name
 *   or null if no such vocabulary exists
 */
function ajax_resources_get_vocabulary_by_name($vocabulary_name) {
  $vocabs = taxonomy_get_vocabularies(NULL);
  foreach ($vocabs as $vocab_object) {
    if ($vocab_object->name == $vocabulary_name) {
      return $vocab_object;
    }
  }
  return NULL;
}
